### ISSUE TITLE
Bug: all_containments_both function 32 bit overflow on NCLS64

### ISSUE THREAD

**Issue by binary-ballistics** [biocore-ntnu/ncls#20]
Hi!
I am currently using NCLS for IP range containment calculations and it yields with 50x performance increase compared to its closest rival, so thanks for this awesome library!

I am casting IPv4 addresses into signed 64 bit numbers (my system is x86_64) which can originally be represented as unsigned 32 bit numbers.  
For example:
IP: 178.244.0.0
int: 3002335232
bin: 10110010111101000000000000000000

Recently, I ran across a problem that when I use all_containments_both function with 64 bit numbers and NCLS64, the numbers are falsely treated as signed 32 bit. In this case for example 3002335232 - 3002597375 interval is mistakenly reported as covered by 1291845632-1292894207. 

* System Info:
OS: 64 bit Ubuntu 18.04
Python: 3.6.8 
NCLS version: 0.0.43 (installed via pip)

* when I check which NCLS is imported it says:
<ncls.src.ncls.NCLS64 object at 0x7f404531cb20>

* Code to reproduce the issue (Comments show displayed results for me)

```python
from ncls import NCLS
import pandas as pd
import numpy as np


df = pd.DataFrame([[3002335232,3002597375],[1291845632, 1292894207]], dtype=int)

print("Column 0 dtype: ", df[0].dtype) # dtype('int64')
print("Column 1 dtype: ", df[1].dtype) # dtype('int64')

print("Intervals:")
print(df)
print("Intervals (32 bit):")
print(df.astype(np.int32))
"""
Intervals:
            0           1
0  3002335232  3002597375
1  1291845632  1292894207
Intervals (32 bit):
            0           1
0 -1292632064 -1292369921
1  1291845632  1292894207
"""

ncls = NCLS(df[0].values, df[1].values, df.index.values)
subs, covers = ncls.all_containments_both(df[0].values, df[1].values, df.index.values)
print("SUBS:", subs)
print("COVERS:", covers)
x, y = subs[0], covers[0]
print("%d-%d contains %d-%d" % (df[0][y], df[1][y], df[0][x], df[1][x]))
"""
SUBS: [0 0 1]
COVERS: [1 0 1]
1291845632-1292894207 contains 3002335232-3002597375
"""

```

**Comment by endrebak** [comment]
Thanks for the feedback :)

I am guessing that this is the offending line: https://github.com/biocore-ntnu/ncls/blob/master/ncls/src/ncls.pyx#L567

I did not know all I needed to know about C integer types when starting this library, sorry.

Will try to fix later today. Need to get some PhD-work done first :)

**Comment by endrebak** [comment]
0.0.46 is just out on PyPI. I also created a simple test for this problem @ https://github.com/biocore-ntnu/ncls/blob/master/tests/test_ncls.py#L29  :)

Feel free to reopen if this did not fix your problems :)

**Comment by binary-ballistics** [comment]
Thanks!

I will check it as soon as possible.

BTW, you have a lovely cat :)

**Comment by endrebak** [comment]
Two actually, but thanks :)
