### ISSUE TITLE
Floating point intervals?

### ISSUE THREAD

**Issue by wmayner** [biocore-ntnu/ncls#28]
Perhaps this is out of scope given the intended application in genomics, but it would be wonderful if this library worked with floating-point ranges as well.

**Comment by endrebak** [comment]
Yes, agreed. There is no reason it cannot be done afaicr, float equality will lead to hiccups, but it likely does not matter.

It is not going to be something I do very soon, only have six months of my PhD. But if enough people tell me here that they desire this functionality and why, I might be persuaded :)

I would accept and help out on prs :)

**Comment by endrebak** [comment]
Try the FNCLS in 0.0.53. See here: https://github.com/biocore-ntnu/ncls/blob/master/examples/test_fncls.py

Would love to hear how you use it and please remember to cite our paper :)
