### ISSUE TITLE
Thread-safety?

### ISSUE THREAD

**Issue by onikolskyy** [biocore-ntnu/ncls#29]
Perhaps trivial, but:
are queries thread safe?
Thanks very much in advance.

**Comment by endrebak** [comment]
Should be; it is just a binary search. It is likely going to be slower than singlethreaded though.

**Comment by onikolskyy** [comment]
Ok, thanks. Why it is likely  to slow down by multiple threads?

**Comment by onikolskyy** [comment]
Thanks, I will :) Actually what I am more up to is true concurrency without IO so it's more multiprocessing
