### ISSUE TITLE
reusing index ?

### ISSUE THREAD

**Issue by jkanche** [biocore-ntnu/ncls#32]
It seems to be that the library currently doesn't support pickle since the c class needs to implement a reduce method

```
python37\lib\site-packages\ncls\src\ncls.cp37-win_amd64.pyd in ncls.src.ncls.NCLS64.__reduce_cython__()

TypeError: no default __reduce__ due to non-trivial __cinit__
```

does the package support any other ways where i can reuse an index once built ?

**Comment by endrebak** [comment]
Thanks for the request.

Building the NCLS should be so fast that you should never want to... Pickling would be slower, most likely. The data in an NCLS is tidy data in native types so the fastest way to serialize it would be to store it as parquet, send, re-read parquet and re-build.

Could you please describe your use-case?

I read your preprint on epiviz with interest btw.

**Comment by jkanche** [comment]
Thank you for the quick response and checking up the epiviz project  :)

My use case here is slightly different. I have a large file (100gigs, similar to a bed file) with intervals (and other fields, but lets ignore these fields for now).  I would like to quickly perform overlap queries, although recreating an ncls index every time i want to perform these queries takes time. So i thought I could pickle the index but seems like that's not possible. 

ncls paper also talks about disk based storage and query. I couldn't find these methods in the python implementation. so was wondering if i might have overlooked at the code.

**Comment by endrebak** [comment]
But if you have multiple queries, can’t you just keep the index in memory? If your data is large pickling still wouldn’t be faster.

If reading all the colums from the bed is what is taking so long, you could just read the three first with pandas to save time.

The size of the file is not what is important here, the number of intervals is.

Do you have a code example?

I won’t be checking my messages until tuesday btw :)
