### ISSUE TITLE
Add intervals dynamically

### ISSUE THREAD

**Issue by mikpom** [biocore-ntnu/ncls#33]
Greetings!

I am interested in incorporating a fast implementation of interval intersection in a project. However I could not figure out from this repo if it is possible to add intervals dynamically. 

If it is please link to a corresponding method. If it is not I believe it is worth mentioning somewhere.

Thanks in advance.

**Comment by endrebak** [comment]
It is not possible, but rebuilding the NCLS is super fast. 

The immutable in the description means that it cannot be changed/updated :)

For a much slower, but still fastish (compared to pure Python) library that allows for this, check out quicksect.

**Comment by mikpom** [comment]
Thanks for your prompt response. 
Always skip the description and go straight to README ))
