### ISSUE TITLE
Implement for Pandas (Multi-)Index on "Interval" data types

### ISSUE THREAD

**Issue by Hoeze** [biocore-ntnu/ncls#34]
Hi, it would be cool to implement this as a Pandas index for "Interval" data types:
https://pandas.pydata.org/pandas-docs/stable/development/internals.html
The geopandas library does a similar thing with the R-Tree index for geometries:
https://github.com/geopandas/geopandas/blob/master/geopandas/sindex.py

Usage example (pseudo-python):
```python
df = pd.DataFrame({...}, dtype={
    "chr": pd.Categorical, 
    "range": pd.Interval, # the Interval column to index
})
# ncls accessor to index the genomic range:
df = df.ncls.set_index(["chr", "range"]) 
# some range operations on the Interval dtype:
df.ncls.intersect(other_df, on=["chr", "range"])
```

Is this doable @endrebak?

**Comment by endrebak** [comment]
Possibly, but I do not like pandas' way of using a custom data type for intervals so I am not going to do it :/

**Comment by Hoeze** [comment]
You do not have to use the custom datatype. You can also have something like `instersect(start="x", end="y")`.
However, I think a `Interval` data type that is representable as `struct[int, int]` would be the natural application of the NCLS:
- No more fiddling with namings like start/end vs start/stop, etc. Instead, better naming with `chr, pos`
- Direct indication as "this is an indexable column"
- Conversion to Apache Arrow interval type
Currently, we use a Postgresql DB with a GiST-indexed `int64range` as replacement for PyRanges.

What do you dislike in the "custom datatype" approach?
