### ISSUE TITLE
Request for official releases

### ISSUE THREAD

**Issue by smoe** [biocore-ntnu/ncls#35]
Hello,
Please kindly consider to have official releases and tag them - this helps a great deal to a) talk about particular versions of your software b) trigger the right updates with conda and regular Linux distributions.
Many thanks and regards!
Steffen

**Comment by endrebak** [comment]
Thanks, I will consider it. For now, the library is stable, mature and will not be updated much though :)

**Comment by smoe** [comment]
Thank you for your kind reply. Here https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository is a bit of help by github. I am actually not ultimately confident about what release date will be shown but since latest changes are still recent, this should all be unproblematic for your users.

**Comment by endrebak** [comment]
0.0.53 is now a tagged release :)
