### ISSUE TITLE
Github Releases?

### ISSUE THREAD

**Issue by nileshpatra** [biocore-ntnu/ncls#36]
Hi,
I need to use this in a project and it would be great if you could tag the releases here.

**Comment by nileshpatra** [comment]
@endrebak please add release tags for ncls as you mentioned [here](https://github.com/pyranges/pyrle/issues/2#issuecomment-645855898). Again, opened this issue so it remains in your TODO :)

**Comment by endrebak** [comment]
https://github.com/biocore-ntnu/ncls/releases/tag/v0.0.53

Did so 20 hours ago. Must have forgotten to ping you :)
