### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by kcleal** [biocore-ntnu/ncls#42]
The line from __init__.py is causing an error:

`ids = np.astype(np.int64)`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kateliddiard/anaconda3/lib/python3.7/site-packages/numpy/__init__.py", line 220, in __getattr__
    "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'astype'`

**Comment by endrebak** [comment]
Thanks!

**Comment by endrebak** [comment]
I am amazed you caught it the second I uploaded it. Thanks! I should have tested before I pushed 👎  I will do so in the future.
