### ISSUE TITLE
Fails to build from source

### ISSUE THREAD

**Issue by nileshpatra** [biocore-ntnu/ncls#44]
Hi @endrebak  thanks for your work on ncls. However, when trying to build it, I get:

```
Error compiling Cython file:
------------------------------------------------------------
...

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cpdef set_difference_helper(self, const int64_t [::1] starts, const int64_t [::1] ends, const int64_t [::1] indexes, const int64_t [::1] nhits,
                                const int64_t[::1] nhits):
                               ^
------------------------------------------------------------

ncls/src/ncls.pyx:450:32: 'nhits' redeclared 

Error compiling Cython file:
------------------------------------------------------------
...


    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cpdef set_difference_helper(self, const int64_t [::1] starts, const int64_t [::1] ends, const int64_t [::1] indexes, const int64_t [::1] nhits,
                                                                                                                        ^
------------------------------------------------------------

ncls/src/ncls.pyx:449:121: Previous declaration is here

Error compiling Cython file:
------------------------------------------------------------
...

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cpdef set_difference_helper(self, const int64_t [::1] starts, const int64_t [::1] ends, const int64_t [::1] indexes, const int64_t [::1] nhits,
                                const int64_t[::1] nhits):
                               ^
------------------------------------------------------------

ncls/src/ncls.pyx:450:32: 'nhits' redeclared 

Error compiling Cython file:
------------------------------------------------------------
...


    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cpdef set_difference_helper(self, const int64_t [::1] starts, const int64_t [::1] ends, const int64_t [::1] indexes, const int64_t [::1] nhits,
                                                                                                                        ^
------------------------------------------------------------
```

Probably something with new gcc. Can you please clean this up?

Thanks!!!
Nilesh

**Comment by endrebak** [comment]
It works when I pip install. Are you building from git?

**Comment by endrebak** [comment]
I see that the github version contains an error: https://github.com/biocore-ntnu/ncls/blob/master/ncls/src/ncls.pyx#L449

Is there any good reason to build from git instead of pip installing? Just curious. Is it something I should expect people do?

**Comment by endrebak** [comment]
New release: https://github.com/biocore-ntnu/ncls/releases/tag/0.0.63-hotfix

**Comment by nileshpatra** [comment]
Hi Endre,

> It works when I pip install. Are you building from git?

Yep.

> Is there any good reason to build from git instead of pip installing? Just curious.

So, I maintain this, pyrle and pyranges for debian. And in debian, we build things from source, so as to distribute
it with the set of packages in archive, and also to distribute the built `.deb` across several acrhitectures (amd64, arm64, armhf, armel, ppc64el, mips{32,64}, s390x and so on}

And hence, we don't take up pre-builds via pip since the idea is to make it `apt` installable, and not `pip` installable.
Let me know if you need more explanation.

> Is it something I should expect people do?

You might expect your downstreams (like debian) to do so :)

BTW, if github is not updated, I could pull "source" package from pypi too, but that's usually a bit suboptimal since several projects do not vendor tests there, and then we need to do  workarounds to pull and run them. They are important for us to run, so as to ensure that the debian package works okay.

> New release: https://github.com/biocore-ntnu/ncls/releases/tag/0.0.63-hotfix

Thanks a lot, this works. I'm in the process of updating pyranges and pyrle too, I'll bug you again in case something does not work again :)
Hope that's OK.

As always, thanks for your work!

Nilesh

**Comment by endrebak** [comment]
Thanks for explaining. I understand now. If you know a way to programmatically create a release I could add it to my git push hook :)

**Comment by nileshpatra** [comment]
I use `git tag -a v<version>` to do this(more details [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging)).
I've never used a hook for doing this admittedly, but I found [this](https://gist.github.com/ajmirsky/1245103) while searching for something similar.
Probably hacking around a little with this can make it relevant for your usecase :)

**Comment by endrebak** [comment]
But that won't create a github tagged release I think. But thanks for the
pointer :)

**Comment by nileshpatra** [comment]
But IIRC, it'd create a GitHub "tag", like [this](https://github.com/nextstrain/augur/tags) for example.
Either tags or releases, anything is fine for me, until I've a clue that a certain commit references a certain tag and I can pull it programmatically :)
