### ISSUE TITLE
sys/time.h preventing installation on Windows

### ISSUE THREAD

**Issue by zkstewart** [biocore-ntnu/ncls#6]
Hello,

This may not necessarily be an issue, but I have been trying to install NCLS on Windows so I can work in this environment without needing to boot up a Linux virtual machine. Whether I attempt to install this using ```pip install ncls``` or via cloning the repository and running ```python setup.py install``` through my normal CMD window or through Cygwin, I encounter errors due to intervaldb.c requiring 'sys/time.h' to be available. The errors look like this

```
ncls/src/intervaldb.c(1): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

From reading online there is no way to get sys/time.h to be recognised on Windows. However, if this is the only thing preventing Windows-compatibility within NCLS, it may be quite easy to replace this requirement with another that is compatible with all the major OS'. I understand if this isn't on the top of your priority list, and for the time being I'm able to continue to modify code which uses NCLS within my virtual machine, but I would find it helpful and it might open up the NCLS code (which is fantastic) to a wider audience.

Regards,
Zac.

**Comment by zkstewart** [comment]
I'm not familiar with anything not Python, but I looked through the intervaldb.c file and it does look like it's just testing code which uses the time functions. I removed just the first line of intervaldb.c which was the include statement for sys/time.h and tried to install with ```python setup.py install``` and, after installing the Windows 10 SDK and making the PATH change suggested here (https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe) I was able to get NCLS to build successfully.

I tried to run code which works in my virtual machine on Windows (within Spyder) with all the same file inputs etc., and received the following error

```
Traceback (most recent call last):

  File "<ipython-input-2-59047c6880fc>", line 1, in <module>
    runfile('D:/Libraries/Documents/GitHub/Genome_analysis_scripts/ggf/gmap_gene_find.py', wdir='D:/Libraries/Documents/GitHub/Genome_analysis_scripts/ggf')

  File "C:\Bioinformatics\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Bioinformatics\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Libraries/Documents/GitHub/Genome_analysis_scripts/ggf/gmap_gene_find.py", line 1024, in <module>
    gff3Ncls, gff3Loc = gff3_parse_ncls(args.annotationFile)

  File "D:/Libraries/Documents/GitHub/Genome_analysis_scripts/ggf/gmap_gene_find.py", line 732, in gff3_parse_ncls
    ncls = NCLS(starts.values, ends.values, ids.values)

  File "ncls\src\ncls.pyx", line 91, in ncls.src.ncls.NCLS.__cinit__ (ncls/src/ncls.c:2804)

ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
```

Without knowing anything about the C languages I'm not sure exactly what the problem is. The values I'm feeding into the NCLS() function are all fine and aren't different between my VM and main PC so I feel confident ruling that out for myself (although I understand if you'd prefer to validate this yourself if you want to look into this error).

Regardless, from looking through the ncls.pyx file, I'm assuming this is unrelated to the sys/time.h issue so it looks as though making edits to intervaldb.c has worked.

**Comment by endrebak** [comment]
It seems like the datatypes are different. On OS X / Linux, longs are used. On windows, long long. I do not have time to look into this, but would accept PRs or be happy for an explanation :)

**Comment by zkstewart** [comment]
No worries. I'll leave it up to you whether this issue is closed or not; the original issue relating to sys/time.h has an easy enough solution. If I was able to I'd love to make NCLS Windows-compatible but for the time being it's not a problem, just a (very) minor inconvenience when I'm working on my home PC.

Thanks,
Zac.

**Comment by lowjiajin** [comment]
@endrebak To fix the datatype issue, we need to modify all declarations and function arguments of `int` and `long` to `int32_t` and `int64_t` respectively, in both `cncls.pxd` and `ncls.pyx`. Additionally, the dtype of any relevant numpy arrays have to be modified to the form `np.int{bits}_t`. 

I've actually modified ncls in this fashion and have verified that together with the deletion of the `sys/time.h` lines mentioned by @zkstewart, ncls seems to work on Windows. If someone is willing to help rewrite the affected tests to work across platforms, I don't mind creating a fork for Windows compatibility and submitting a PR.

**Comment by endrebak** [comment]
Cool. Will try to fix later today. This library is actually tested indirectly in the pyranges-repo, the only test on travis is that it installs IIRC.

**Comment by endrebak** [comment]
I did not see that you offered to help out. Please create a PR :)

**Comment by lowjiajin** [comment]
Is ncls a git submodule in pyranges? I have yet to run the test suite in pyranges on the latest changes, perhaps you could help with that. Thanks!

**Comment by huhumiily** [comment]
It seems that there are a lot of people who can't install ncls under winsows, and most of them are because of (sys/time.h: No such file or directory). Can the author find a way to help, thank you.

**Comment by endrebak** [comment]
Merged the pr. Try the github version and report back please.

**Comment by endrebak** [comment]
Broke the build. I reverted the PR.

**Comment by endrebak** [comment]
If someone makes a working PR I’ll merge it. Can you try @huhumiily ?

**Comment by endrebak** [comment]
Ive tried removing time.h. Can someone try git clone and Python setup.py install and check if it works?

**Comment by zkstewart** [comment]
Hi!

It took me a bit of time to get around to trying this out, but I attempted to make one of my previous scripts Windows-compatible with ncls==0.0.44 but ran into an error which is below.

```
Traceback (most recent call last):
  File "deGRIT.py", line 865, in <module>
    ncls, gmapLoc = gmap_parse_ncls(args.gmapFile, minCutoff)
  File "deGRIT.py", line 503, in gmap_parse_ncls
    ncls = NCLS(starts.values, ends.values, ids.values)
  File "C:\Bioinformatics\Anaconda3\lib\site-packages\ncls\__init__.py", line 9, in NCLS
    return NCLS64(starts, ends, ids)
  File "ncls/src/ncls.pyx", line 34, in ncls.src.ncls.NCLS64.__cinit__
    def __cinit__(self, const long [::1] starts=None, const long [::1] ends=None, const long [::1] ids=None):
ValueError: Buffer dtype mismatch, expected 'const long' but got 'long long'
```

I'm not too familiar with C so an unsure what this is telling me precisely. I did, however, decide to uninstall ncls and reinstall it with no success, so I don't think it's related to some remnant files from previous versions.

**Comment by endrebak** [comment]
Thanks :) It basically says that you sent it a different type than expected. Can you post the code used please?

**Comment by zkstewart** [comment]
Sure, I'll try my best to provide any information needed to sort this out.

The full code I used is here https://github.com/zkstewart/deGRIT/blob/master/deGRIT.py, but the precise function being used is below.

```
def gmap_parse_ncls(gmapFile, cutoff):
        gmapLoc = {}
        starts = []
        ends = []
        ids = []
        ongoingCount = 0
        with open(gmapFile, 'r') as fileIn:
                for line in fileIn:
                        # Skip unneccessary lines
                        if line.startswith('#'):
                                continue
                        sl = line.split('\t')
                        if sl[2] != 'cDNA_match':
                                continue
                        # Get details from line including start, stop, and orientation
                        contigID = sl[0]
                        if not sl[8].startswith('ID=blat.proc'): # May as well make the code compatible with BLAT.
                                geneID = sl[8].split(';')[1][5:] # Start from 5 to get rid of 'Name='.
                        else:
                                geneID = sl[8].split(';')[1].split()[0][7:] # Start from 7 to get rid of 'Target='.
                        contigStart = int(sl[3])
                        contigStop = int(sl[4])
                        identity = float(sl[5])
                        if identity < cutoff: # Speed up program by only holding onto hits that will pass our cutoff check.
                                continue
                        orient = sl[6]
                        if not sl[8].startswith('ID=blat.proc'):
                                transStart = int(sl[8].split(';')[2].split()[1])
                                transStop = int(sl[8].split(';')[2].split()[2])
                        else:
                                transStart = int(sl[8].split(';')[1].split()[1])
                                transStop = int(sl[8].split(';')[1].split()[2])
                        # Add to our NCLS... Note: We index using ranges since it provides an easy way to retrieve GMAP matches by coordinates. Since these coordinates aren't unique, we filter any results returned by their contig ID.
                        starts.append(contigStart)
                        ends.append(contigStop+1) # NCLS indexes 0-based, so +1 to make this more logically compliant with gff3 1-based system.
                        ids.append(ongoingCount)
                        gmapLoc[ongoingCount] = [contigStart, contigStop, transStart, transStop, orient, geneID, identity, contigID]
                        ongoingCount += 1
        # Build the NCLS object
        starts = pd.Series(starts)
        ends = pd.Series(ends)
        ids = pd.Series(ids)
        ncls = NCLS(starts.values, ends.values, ids.values)
        return ncls, gmapLoc
```
For your reference, the gmapFile value corresponds to a file path, the contents of which are in GFF3 format like such:

```
PGA_scaffold2__45_contigs__length_23673736	PGA_assembly.fasta.gmap	cDNA_match	12723202	12723492	98	-	.	ID=act_scaff_75.path1;Name=act_scaff_75;Target=act_scaff_75 1 291;Gap=M291
###								
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	10402919	10403075	98	-	.	ID=act_scaff_189.path1;Name=act_scaff_189;Target=act_scaff_189 1 157;Gap=M157
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	10402127	10402362	100	-	.	ID=act_scaff_189.path1;Name=act_scaff_189;Target=act_scaff_189 158 393;Gap=M236
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	10401256	10401523	100	-	.	ID=act_scaff_189.path1;Name=act_scaff_189;Target=act_scaff_189 394 661;Gap=M268
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	10399959	10400608	100	-	.	ID=act_scaff_189.path1;Name=act_scaff_189;Target=act_scaff_189 662 1311;Gap=M650
###								
PGA_scaffold15__27_contigs__length_11533743	PGA_assembly.fasta.gmap	cDNA_match	10407067	10407653	90	+	.	ID=act_scaff_209.path1;Name=act_scaff_209;Target=act_scaff_209 1 592;Gap=M409 I5 M178
###								
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	2475625	2475786	100	+	.	ID=act_scaff_158.path1;Name=act_scaff_158;Target=act_scaff_158 1 162;Gap=M162
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	2479022	2479284	100	+	.	ID=act_scaff_158.path1;Name=act_scaff_158;Target=act_scaff_158 163 425;Gap=M263
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	2480012	2480215	100	+	.	ID=act_scaff_158.path1;Name=act_scaff_158;Target=act_scaff_158 426 629;Gap=M204
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	2482530	2482707	100	+	.	ID=act_scaff_158.path1;Name=act_scaff_158;Target=act_scaff_158 630 807;Gap=M178
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	2487975	2488128	100	+	.	ID=act_scaff_158.path1;Name=act_scaff_158;Target=act_scaff_158 808 961;Gap=M154
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	2488688	2488760	100	+	.	ID=act_scaff_158.path1;Name=act_scaff_158;Target=act_scaff_158 962 1034;Gap=M73
PGA_scaffold13__45_contigs__length_12533684	PGA_assembly.fasta.gmap	cDNA_match	2489570	2489756	100	+	.	ID=act_scaff_158.path1;Name=act_scaff_158;Target=act_scaff_158 1035 1221;Gap=M187
###								
```
And cutoff is just an integer which defaults to being 97. I'm self-taught when it comes to coding so I'm unsure if the function is otherwise readable - if you want some help interpreting it, I'll have a go at it.

Lastly, the whole program works as intended on Ubuntu and a SUSE HPC system. Let me know if you need anything else =).

**Comment by endrebak** [comment]
Try


starts = pd.Series(starts, dtype=np.int64) # np is numpy


Thanks btw

**Comment by endrebak** [comment]
And similarly for the others

**Comment by zkstewart** [comment]
Changing the last block of code to be this:

```
# Build the NCLS object
starts = pd.Series(starts, dtype=np.int64)
ends = pd.Series(ends, dtype=np.int64)
ids = pd.Series(ids, dtype=np.int64)
ncls = NCLS(starts.values, ends.values, ids.values)
```

Results in the same error i.e.,

```
ncls = NCLS(starts.values, ends.values, ids.values)
Traceback (most recent call last):

  File "<ipython-input-16-97f0f0bbed09>", line 1, in <module>
    ncls = NCLS(starts.values, ends.values, ids.values)

  File "C:\Bioinformatics\Anaconda3\lib\site-packages\ncls\__init__.py", line 9, in NCLS
    return NCLS64(starts, ends, ids)

  File "ncls/src/ncls.pyx", line 34, in ncls.src.ncls.NCLS64.__cinit__

ValueError: Buffer dtype mismatch, expected 'const long' but got 'long long'
```

Also, when I call starts.values to check out the array, it provides the same details whether I add dtype=np.int64 or not i.e.,

```
array([ 8775539,   689791,  4780803, ...,  5980239,  7062393, 10741040],
      dtype=int64)
```
So I assume pandas has this dtype value as its default.

**Comment by endrebak** [comment]
I appreciate that you took the time to try. I think this might be the solution: https://github.com/akaszynski/pyansys/issues/14

but I am working hard on finishing my phd. Dunno if others can try a simple PR, otherwise I would do it eventually :)

**Comment by endrebak** [comment]
Try again with 0.0.45 please :)

**Comment by zkstewart** [comment]
Might've got the magic right! I'll have to give it a more thorough test tomorrow morning to make sure that my program provides identical results on the Unix system, but ncls seems to be running without incident on Windows right now and doing what I expect it to.

**Comment by endrebak** [comment]
Hooray. Keeping this open until more people confirm :)

**Comment by endrebak** [comment]
Feel free to reopen if something fails on win :)
